language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  slack:
    secure: FJ7mhAd58zs8SC562d6LqaZZZ4xp7McLdCjpa4vzcEWUo24wTGyIrBBRKdBD7ZOBteRZJZfzh97kysDAMgPgyc8aYVkloZD+Uk1B2mgbX8CYFQORrPz3jSxx7eGF2lohV06GcgnB8ZHHwYNxCTMIuQ2IHhSCl8aAIikY6tkr/I/LbzxA0gpapfLLH0EUz/uWt28sab/bx6YwcRMkzhNg3i0NTRHGRxtnUG9HTZ9hLy/3VbVVJ/0wFnVqMpM3/+J5ckMcf5zjbuWYAwf/l0TQt+tKpQUOn785Cmd0s+IDSnkLfF+WpwGC0WruLbnvLRo0EhJpsTIqhgYpPbaZsCXOb7HI4rfAe+G8KUUW7uZWtYoyUTgtDde6l1AVCV3TLtOgHTRcj4qkJoQhSwpkKjiK4LqO4788758mzcNp/VnI3d+BgOn/Ki2Pv5x4xLw1MVKjI19t3uSAZuBdKn6HxlVyOhP5MJ7SlTZh/GIpUBF7aIRV5eYnyzMvoU3x/0rRF0QGiqHmWpu9q48dBdTMd08l3kul3C1LfBAhJ8+NSmlAA4KTXJFuqVwyzQdnAG5Dx71wccg4y49X1i1KVsvP6d3a5S8zijSETMDEvYqNN9EuHlCdR34/093/qfywKU0U/uG7/ltTs8Kh/wPcMfZusBmIjDCJRb5lNmL80sZPXvMjyHk=
